[connections]
termboard = "postgres://saltchicken:password@master/termboard"
pgnotes = "postgresql://saltchicken:password@10.0.0.5:5432/pgnotes"
stock = "postgresql://saltchicken:password@10.0.0.5:5432/stock"
