[python]
include = ["*.py"]
exclude = ["*.pyc", "__pycache__/", ".venv/"]

[cpp]
include = ["*.cpp"]
exclude = ["node_modules", "dist", "build"]

[rust]
include = ["*.rs"]
exclude = ["target"]
include_in_tree = ["Cargo.toml", "Cargo.lock"]

[python-react]
include = ["*.py", "*.toml", "*.jsx", "*.html", "*.css", "*.js", "*.ts", "*.tsx"]

[frameshader]
include = ["*.cpp", "*.txt", "*.vert", "*.frag"]
include_in_tree = ["glad.c", "*.h", "*.png", "*.onnx"]

[opengl]
include = ["*.cpp", "*.txt", "*.vert", "*.frag"]
include_in_tree = ["glad.c", "*.h"]

[code-context]
include = ["*.rs", "*.toml"]

[ComfyUI-Prompter]
include = ["*.py", "*.json", "*.js"]

['code-context.nvim']
include = ["*.lua"]

['font_atlas_generator']
include = ["*.py", "*.toml"]
exclude = ["*.pyc", "__pycache__/", ".venv/"]

[aflames]
include = ["*.cpp", "*.txt", "*.h", "*.vert", "*.frag", "*.comp", "*.ini"]
exclude = ["glm/", "imgui/", "build"]
include_in_tree = ["glad.c", "glad.h"]

[opengl-template]
include = ["*.cpp", "*.txt", "*.h", "*.vert", "*.frag", "*.comp", "*.toml", "*.lua"]
exclude = ["build", "TODO.txt"]
include_in_tree = ["glad.c", "glad.h", "stb_image.h", "miniaudio.h", "CMakeLists.txt"]

[pipetest]
include = ["*.cpp", "*.txt"]
exclude = ["node_modules", "dist", "build"]

[aetherbox]
include = ["*.rs", "*.toml", "*vert", "*.frag", "*.wgsl", "*.html"]
exclude = ["target", "build"]
include_in_tree = ["*.png"]

[trans-rust-wgpu]
include = ["*.rs", "*.toml", "*vert", "*.frag", "*.wgsl", "*.html"]
exclude = ["target", "build"]
include_in_tree = ["*.png"]

[blog_os]
include = ["*.rs", "*.toml", "*.json", ".cargo/*" ]
exclude = [".github*", "blog*"]

[push2]
include = ["*.rs", "*.toml", "*.ron", "*.qml"]
exclude = ["target", "build", "examples"]

[moonlight-android]
include = ["*.java", "*.toml"]

[WatchTestApp]
include = ["*receiver.py", "*build.gradle.kts", "*AndroidManifest.xml", "*MainActivity.kt", "*styles.xml"]

[runpod_runner]
include = ["*.py", "start.sh", "Dockerfile", "*.toml", ".dockerignore"]

[midi-model]
include = ["*.py", "*.sh"]
include_in_tree = ["*.safetensors", "*.json", "MIDI.py"]
