[python]
include = ["*.py"]
exclude = ["*.pyc", "__pycache__/", ".venv/"]

[cpp]
include = ["*.cpp"]
exclude = ["node_modules", "dist", "build"]

[rust]
include = ["*.rs"]
exclude = ["target"]
include_in_tree = ["Cargo.toml", "Cargo.lock"]

[frameshader]
include = ["*.cpp", "*.txt", "*.vert", "*.frag"]
include_in_tree = ["glad.c", "*.h", "*.png", "*.onnx"]

[opengl]
include = ["*.cpp", "*.txt", "*.vert", "*.frag"]
include_in_tree = ["glad.c", "*.h"]

[code_context]
include = ["*.py", "*.toml"]
exclude = ["*.pyc", "__pycache__/", ".venv/", "tests"]

['code-context.nvim']
include = ["*.lua"]

['font_atlas_generator']
include = ["*.py", "*.toml"]
exclude = ["*.pyc", "__pycache__/", ".venv/"]

['gstreaming']
include = ["*.cpp"]
exclude = ["node_modules", "dist", "build"]

[aflames]
include = ["*.cpp", "*.txt", "*.h", "*.vert", "*.frag", "*.comp", "*.ini"]
exclude = ["glm/", "imgui/", "build"]
include_in_tree = ["glad.c", "glad.h"]

[git_code_context]
include = ["*.py", "*.toml"]
exclude = ["*.pyc", "__pycache__/", ".venv/", "tests"]

[opengl-template]
include = ["*.cpp", "*.txt", "*.h", "*.vert", "*.frag", "*.comp", "*.toml", "*.lua"]
exclude = ["build", "TODO.txt"]
include_in_tree = ["glad.c", "glad.h", "stb_image.h", "miniaudio.h", "CMakeLists.txt"]

[pipetest]
include = ["*.cpp", "*.txt"]
exclude = ["node_modules", "dist", "build"]

[oxide]
include = ["*.rs", "*.toml"]
exclude = ["target", "build"]

[wasm-gl]
include = ["*.rs", "*.toml", "*vert", "*.frag", "*.wgsl", "*.html"]
exclude = ["target", "build"]
include_in_tree = ["*.png"]

[rust-gl]
include = ["*.rs", "*.toml", "*vert", "*.frag", "*.wgsl", "*.html"]
exclude = ["target", "build"]
include_in_tree = ["*.png"]


[rust-wgpu]
include = ["*.rs", "*.toml", "*vert", "*.frag", "*.wgsl", "*.html"]
exclude = ["target", "build"]
include_in_tree = ["*.png"]

[aetherbox]
include = ["*.rs", "*.toml", "*vert", "*.frag", "*.wgsl", "*.html"]
exclude = ["target", "build"]
include_in_tree = ["*.png"]

[trans-rust-wgpu]
include = ["*.rs", "*.toml", "*vert", "*.frag", "*.wgsl", "*.html"]
exclude = ["target", "build"]
include_in_tree = ["*.png"]



[libinput_hello]
include = ["*rs", "*.toml"]
exclude = ["target", "build"]

[python-elgato-streamdeck]
include = ["*py", "*.toml"]

[delete]
include = ["*.rs", "*.toml"]
exclude = ["target", "build"]

[proclink]
include = ["*.rs", "*.toml"]

[pipelink-audio]
include = ["*.rs", "*.toml"]

[dash]
include = ["*.rs", "*.toml"]

[projects]
include = ["*.rs", "*.toml"]


[plx]
include = ["*.rs", "*.toml"]

[rust-context]
include = ["*.rs", "*.toml"]

[kern]
include = ["*.rs", "*.toml", "*.json", ".cargo/*"]

[blog_os]
include = ["*.rs", "*.toml", "*.json", ".cargo/*" ]
exclude = [".github*", "blog*"]

[rim]
include = ["*.rs", "*.toml"]

[soundboard]
include = ["*.rs", "*.toml"]
include_in_tree = ["*.png"]
